name: Deploy
on: workflow_dispatch
env:
  OUTPUT: build
  LANG: es_ES.UTF-8
jobs:
  build:
    name: Build lektor website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Add locale ES
        run: |
          sudo locale-gen es_ES.UTF-8
          locale -a
      - name: Install requirements
        run: |
          ./scripts/install
          sudo apt-get -y install gettext python3-babel
      - name: Build lektor website
        run: |
          source .venv/bin/activate
          locale
          lektor build -f webpack -O '${{ env.OUTPUT }}'
      - name: Deploy lektor website
        run: |
          source .venv/bin/activate
          lektor deploy -O '${{ env.OUTPUT }}' ghpages-https
        env:
          LEKTOR_DEPLOY_USERNAME: ${{ github.actor }}
          LEKTOR_DEPLOY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
